---@meta

---@class _.lspconfig.settings.cspell_ls.CSpell.Advanced.Feature
---Used to work around bugs in Reference Providers and Rename Providers.
---Anything matching the provided Regular Expression will be removed from the text
---before sending it to the Rename Provider.
---
---See: [Markdown: Fixing spelling issues in Header sections changes the entire line · Issue #1987](https://github.com/streetsidesoftware/vscode-spell-checker/issues/1987)
---
---It is unlikely that you would need to edit this setting. If you need to, please open an issue at
---[Spell Checker Issues](https://github.com/streetsidesoftware/vscode-spell-checker/issues)
---
---This feature is used in connection with `#cSpell.advanced.feature.useReferenceProviderWithRename#`
---@field useReferenceProviderRemove? string
---Use the Reference Provider when fixing spelling issues with the Rename Provider.
---This feature is used in connection with `#cSpell.fixSpellingWithRenameProvider#`
---@field useReferenceProviderWithRename? boolean

---@class _.lspconfig.settings.cspell_ls.CSpell.Advanced
---@field feature? _.lspconfig.settings.cspell_ls.CSpell.Advanced.Feature

---Decoration for dark themes.
---
---See:
---- `#cSpell.overviewRulerColor#`
---- `#cSpell.textDecoration#`
---@class _.lspconfig.settings.cspell_ls.CSpell.Dark
---The CSS color used to show issues in the ruler.
---
---Depends upon `#cSpell.useCustomDecorations#`.
---Disable the ruler by setting `#cSpell.showInRuler#` to `false`.
---
---See:
---- [`<color>` CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)
---- [CSS Colors, W3C Schools](https://www.w3schools.com/cssref/css_colors.php)
---- Hex colors
---
---Examples:
---- `green`
---- `DarkYellow`
---- `#ffff0080` - semi-transparent yellow.
---- `rgb(255 153 0 / 80%)`
---
---```lua
---default = "#348feb80"
---```
---@field overviewRulerColor? string
---The CSS Style used to decorate spelling issues. Depends upon `#cSpell.useCustomDecorations#`.
---
---This setting is used to manually configure the text decoration. If it is not set, the following settings are used:
---- `#cSpell.textDecorationLine#` to pick the line type
---- `#cSpell.textDecorationStyle#` to pick the style
---- `#cSpell.textDecorationColor#` to set the color
---- `#cSpell.textDecorationThickness#` to set the thickness.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---
---Format:  `<line> [style] <color> [thickness]`
---
---- line - `underline`, `overline`, see: [text-decoration-line, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line)
---- style - `solid`, `wavy`, `dotted`, see: [text-decoration-style, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---- thickness - see: [text-decoration-thickness, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)
---
---Examples:
---- `underline green`
---- `underline dotted yellow 0.2rem`
---- `underline wavy #ff0c 1.5px` - Wavy underline with 1.5px thickness in semi-transparent yellow.
---
---To change the ruler color, use `#cSpell.overviewRulerColor#`.
---@field textDecoration? string
---The decoration color for normal spelling issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---To change the ruler color, use `#cSpell.overviewRulerColor#`.
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#348feb"
---```
---@field textDecorationColor? string
---The decoration color for flagged issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#f44"
---```
---@field textDecorationColorFlagged? string
---The decoration color for spelling suggestions.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---Common Format: `#RGBA` or `#RRGGBBAA` or `#RGB` or `#RRGGBB`
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#cf88"
---```
---@field textDecorationColorSuggestion? string
---The CSS line type used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- line - `underline`, `overline`, see: [text-decoration-line, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line)
---
---```lua
---default = "underline"
---```
---@field textDecorationLine? "underline" | "overline" | "line-through"
---The CSS line style used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- style - `solid`, `wavy`, `dotted`, see: [text-decoration-style, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style)
---
---```lua
---default = "dashed"
---```
---@field textDecorationStyle? "solid" | "wavy" | "dotted" | "dashed" | "double"
---The CSS line thickness used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- thickness - see: [text-decoration-thickness, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)
---
---Examples:
---- `auto`
---- `from-font`
---- `0.2rem`
---- `1.5px`
---- `10%`
---
---```lua
---default = "auto"
---```
---@field textDecorationThickness? string

---Control which notifications are displayed.
---
---See:
---- `#cSpell.blockCheckingWhenLineLengthGreaterThan#`
---- `#cSpell.blockCheckingWhenTextChunkSizeGreaterThan#`
---- `#cSpell.blockCheckingWhenAverageChunkSizeGreaterThan#`
---
---```lua
---default = {
---  ["Average Word Length too Long"] = true,
---  ["Lines too Long"] = true,
---  ["Maximum Word Length Exceeded"] = true
---}
---```
---@class _.lspconfig.settings.cspell_ls.CSpell.EnabledNotifications
---Enable notifications if the average word size is too high.
---@field ["Average Word Length too Long"]? boolean
---Enable notifications if the line is too long.
---@field ["Lines too Long"]? boolean
---Enable notifications if the maximum word length is exceeded.
---@field ["Maximum Word Length Exceeded"]? boolean

---Specify compatible engine versions.
---
---This allows dictionaries and other components to specify the versions of engines (like cspell) they are compatible with.
---
---It does not enforce compatibility, it is up to the client to use this information as needed.
---@class _.lspconfig.settings.cspell_ls.CSpell.Engines
---The VSCode Spell Checker version predicate.
---@field ["code-spell-checker"]? string
---CSpell version predicate.
---@field cspell? string

---@class _.lspconfig.settings.cspell_ls.CSpell.Experimental
---Show Regular Expression Explorer
---@field enableRegexpView? boolean
---Experiment with executeDocumentSymbolProvider.
---This feature is experimental and will be removed in the future.
---@field symbols? boolean

---Decoration for light themes.
---
---See:
---- `#cSpell.overviewRulerColor#`
---- `#cSpell.textDecoration#`
---@class _.lspconfig.settings.cspell_ls.CSpell.Light
---The CSS color used to show issues in the ruler.
---
---Depends upon `#cSpell.useCustomDecorations#`.
---Disable the ruler by setting `#cSpell.showInRuler#` to `false`.
---
---See:
---- [`<color>` CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)
---- [CSS Colors, W3C Schools](https://www.w3schools.com/cssref/css_colors.php)
---- Hex colors
---
---Examples:
---- `green`
---- `DarkYellow`
---- `#ffff0080` - semi-transparent yellow.
---- `rgb(255 153 0 / 80%)`
---
---```lua
---default = "#348feb80"
---```
---@field overviewRulerColor? string
---The CSS Style used to decorate spelling issues. Depends upon `#cSpell.useCustomDecorations#`.
---
---This setting is used to manually configure the text decoration. If it is not set, the following settings are used:
---- `#cSpell.textDecorationLine#` to pick the line type
---- `#cSpell.textDecorationStyle#` to pick the style
---- `#cSpell.textDecorationColor#` to set the color
---- `#cSpell.textDecorationThickness#` to set the thickness.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---
---Format:  `<line> [style] <color> [thickness]`
---
---- line - `underline`, `overline`, see: [text-decoration-line, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line)
---- style - `solid`, `wavy`, `dotted`, see: [text-decoration-style, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---- thickness - see: [text-decoration-thickness, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)
---
---Examples:
---- `underline green`
---- `underline dotted yellow 0.2rem`
---- `underline wavy #ff0c 1.5px` - Wavy underline with 1.5px thickness in semi-transparent yellow.
---
---To change the ruler color, use `#cSpell.overviewRulerColor#`.
---@field textDecoration? string
---The decoration color for normal spelling issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---To change the ruler color, use `#cSpell.overviewRulerColor#`.
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#348feb"
---```
---@field textDecorationColor? string
---The decoration color for flagged issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#f44"
---```
---@field textDecorationColorFlagged? string
---The decoration color for spelling suggestions.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---Common Format: `#RGBA` or `#RRGGBBAA` or `#RGB` or `#RRGGBB`
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#cf88"
---```
---@field textDecorationColorSuggestion? string
---The CSS line type used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- line - `underline`, `overline`, see: [text-decoration-line, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line)
---
---```lua
---default = "underline"
---```
---@field textDecorationLine? "underline" | "overline" | "line-through"
---The CSS line style used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- style - `solid`, `wavy`, `dotted`, see: [text-decoration-style, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style)
---
---```lua
---default = "dashed"
---```
---@field textDecorationStyle? "solid" | "wavy" | "dotted" | "dashed" | "double"
---The CSS line thickness used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- thickness - see: [text-decoration-thickness, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)
---
---Examples:
---- `auto`
---- `from-font`
---- `0.2rem`
---- `1.5px`
---- `10%`
---
---```lua
---default = "auto"
---```
---@field textDecorationThickness? string

---Specify which fields from `.vscode/settings.json` are passed to the spell checker.
---This only applies when there is a CSpell configuration file in the workspace and
---`#cSpell.mergeCSpellSettings#` is `true`.
---
---Values:
---- `{ flagWords: true, userWords: false }` - Always allow `flagWords`, but never allow `userWords`.
---
---Example:
---```jsonc
---"cSpell.mergeCSpellSettingsFields": { "userWords": false }
---```
---
---```lua
---default = {
---  allowCompoundWords = true,
---  caseSensitive = true,
---  dictionaries = true,
---  dictionaryDefinitions = true,
---  enableGlobDot = true,
---  features = true,
---  files = true,
---  flagWords = true,
---  gitignoreRoot = true,
---  globRoot = true,
---  ignorePaths = true,
---  ignoreRegExpList = true,
---  ignoreWords = true,
---  import = true,
---  includeRegExpList = true,
---  language = true,
---  languageId = true,
---  languageSettings = true,
---  loadDefaultConfiguration = true,
---  minWordLength = true,
---  noConfigSearch = true,
---  noSuggestDictionaries = true,
---  numSuggestions = true,
---  overrides = true,
---  patterns = true,
---  pnpFiles = true,
---  reporters = true,
---  suggestWords = true,
---  useGitignore = true,
---  usePnP = true,
---  userWords = true,
---  validateDirectives = true,
---  words = true
---}
---```
---@class _.lspconfig.settings.cspell_ls.CSpell.MergeCSpellSettingsFields
---@field allowCompoundWords? boolean
---@field caseSensitive? boolean
---@field dictionaries? boolean
---@field dictionaryDefinitions? boolean
---@field enableGlobDot? boolean
---@field features? boolean
---@field files? boolean
---@field flagWords? boolean
---@field gitignoreRoot? boolean
---@field globRoot? boolean
---@field ignorePaths? boolean
---@field ignoreRegExpList? boolean
---@field ignoreWords? boolean
---@field import? boolean
---@field includeRegExpList? boolean
---@field language? boolean
---@field languageId? boolean
---@field languageSettings? boolean
---@field loadDefaultConfiguration? boolean
---@field minWordLength? boolean
---@field noConfigSearch? boolean
---@field noSuggestDictionaries? boolean
---@field numSuggestions? boolean
---@field overrides? boolean
---@field patterns? boolean
---@field pnpFiles? boolean
---@field reporters? boolean
---@field suggestWords? boolean
---@field useGitignore? boolean
---@field usePnP? boolean
---@field userWords? boolean
---@field validateDirectives? boolean
---@field words? boolean

---@class _.lspconfig.settings.cspell_ls.CSpell
---@field advanced? _.lspconfig.settings.cspell_ls.CSpell.Advanced
---Enable / Disable allowing word compounds.
---- `true` means `arraylength` would be ok
---- `false` means it would not pass.
---
---Note: this can also cause many misspelled words to seem correct.
---@field allowCompoundWords? boolean
---Control which file schemes will be checked for spelling (VS Code must be restarted for this setting to take effect).
---
---
---Some schemes have special meaning like:
---- `untitled` - Used for new documents that have not yet been saved
---- `vscode-notebook-cell` - Used for validating segments of a Notebook.
---- `vscode-userdata` - Needed to spell check `.code-snippets`
---- `vscode-scm` - Needed to spell check Source Control commit messages.
---- `comment` - Used for new comment editors.
---@field allowedSchemas? string[]
---If a `cspell` configuration file is updated, format the configuration file
---using the VS Code Format Document Provider. This will cause the configuration
---file to be saved prior to being updated.
---@field autoFormatConfigFile? boolean
---Enable / Disable autocorrect while typing.
---@field autocorrect? boolean
---The maximum average length of chunks of text without word breaks.
---
---
---A chunk is the characters between absolute word breaks.
---Absolute word breaks match: `/[\s,{}[\]]/`
---
---
---**Error Message:** _Average word length is too long._
---
---
---If you are seeing this message, it means that the file contains mostly long lines
---without many word breaks.
---
---
---Hide this message using `#cSpell.enabledNotifications#`
---
---```lua
---default = 200
---```
---@field blockCheckingWhenAverageChunkSizeGreaterThan? number
---The maximum line length.
---
---
---Block spell checking if lines are longer than the value given.
---This is used to prevent spell checking generated files.
---
---
---**Error Message:** _Lines are too long._
---
---
---Hide this message using `#cSpell.enabledNotifications#`
---
---```lua
---default = 20000
---```
---@field blockCheckingWhenLineLengthGreaterThan? number
---The maximum length of a chunk of text without word breaks.
---
---
---It is used to prevent spell checking of generated files.
---
---
---A chunk is the characters between absolute word breaks.
---Absolute word breaks match: `/[\s,{}[\]]/`, i.e. spaces or braces.
---
---
---**Error Message:** _Maximum word length exceeded._
---
---
---If you are seeing this message, it means that the file contains a very long line
---without many word breaks.
---
---
---Hide this message using `#cSpell.enabledNotifications#`
---
---```lua
---default = 1000
---```
---@field blockCheckingWhenTextChunkSizeGreaterThan? number
---Determines if words must match case and accent rules.
---
---- `false` - Case is ignored and accents can be missing on the entire word.
---  Incorrect accents or partially missing accents will be marked as incorrect.
---  **Note:** Some languages like Portuguese have case sensitivity turned on by default.
---  You must use `#cSpell.languageSettings#` to turn it off.
---- `true` - Case and accents are enforced by default.
---@field caseSensitive? boolean
---Set the maximum number of blocks of text to check.
---Each block is 1024 characters.
---
---```lua
---default = 500
---```
---@field checkLimit? number
---By default, the spell checker checks only enabled file types. Use `#cSpell.enabledFileTypes#`
---to turn on / off various file types.
---
---When this setting is `false`, all file types are checked except for the ones disabled by `#cSpell.enabledFileTypes#`.
---See `#cSpell.enabledFileTypes#` on how to disable a file type.
---
---```lua
---default = true
---```
---@field checkOnlyEnabledFileTypes? boolean
---Spell check VS Code system files.
---These include:
---- `vscode-userdata:/**/settings.json`
---- `vscode-userdata:/**/keybindings.json`
---@field checkVSCodeSystemFiles? boolean
---Define custom dictionaries to be included by default.
---If `addWords` is `true` words will be added to this dictionary.
---
---
---**Example:**
---
---```js
---"cSpell.customDictionaries": {
---  "project-words": {
---    "name": "project-words",
---    "path": "${workspaceRoot}/project-words.txt",
---    "description": "Words used in this project",
---    "addWords": true
---  },
---  "custom": true, // Enable the `custom` dictionary
---  "internal-terms": false // Disable the `internal-terms` dictionary
---}
---```
---@field customDictionaries? table
---Define custom dictionaries to be included by default for the folder.
---If `addWords` is `true` words will be added to this dictionary.
---@field customFolderDictionaries? any[]
---Define custom dictionaries to be included by default for the user.
---If `addWords` is `true` words will be added to this dictionary.
---@field customUserDictionaries? any[]
---Define custom dictionaries to be included by default for the workspace.
---If `addWords` is `true` words will be added to this dictionary.
---@field customWorkspaceDictionaries? any[]
---Decoration for dark themes.
---
---See:
---- `#cSpell.overviewRulerColor#`
---- `#cSpell.textDecoration#`
---@field dark? _.lspconfig.settings.cspell_ls.CSpell.Dark
---The Diagnostic Severity Level determines how issues are shown in the Problems Pane and within the document.
---Set the level to `Hint` to hide the issues from the Problems Pane.
---
---Note: `#cSpell.useCustomDecorations#` must be `false` to use VS Code Diagnostic Severity Levels.
---
---See: [VS Code Diagnostic Severity Level](https://code.visualstudio.com/api/references/vscode-api#DiagnosticSeverity)
---
---```lua
---default = "Information"
---```
---@field diagnosticLevel? "Error" | "Warning" | "Information" | "Hint"
---Flagged word issues found by the spell checker are marked with a Diagnostic Severity Level. This affects the color of the squiggle.
---By default, flagged words will use the same diagnostic level as general issues. Use this setting to customize them.
---
---See: [VS Code Diagnostic Severity Level](https://code.visualstudio.com/api/references/vscode-api#DiagnosticSeverity)
---@field diagnosticLevelFlaggedWords? "Error" | "Warning" | "Information" | "Hint"
---Optional list of dictionaries to use.
---
---Each entry should match the name of the dictionary.
---
---To remove a dictionary from the list add `!` before the name.
---i.e. `!typescript` will turn off the dictionary with the name `typescript`.
---
---
---Example:
---
---```jsonc
---// Enable `lorem-ipsum` and disable `typescript`
---"cSpell.dictionaries": ["lorem-ipsum", "!typescript"]
---```
---@field dictionaries? string[]
---Define custom dictionaries.
---If `addWords` is `true` words will be added to this dictionary.
---
---This setting is subject to User/Workspace settings precedence rules: [Visual Studio Code User and Workspace Settings](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence).
---
---It is better to use `#cSpell.customDictionaries#`
---
---**Example:**
---
---```js
---"cSpell.dictionaryDefinitions": [
---  {
---    "name": "project-words",
---    "path": "${workspaceRoot}/project-words.txt",
---    "description": "Words used in this project",
---    "addWords": true
---  }
---]
---```
---@field dictionaryDefinitions? any[]
---Use the VS Code Diagnostic Collection to render spelling issues.
---
---With some edit boxes, like the source control message box, the custom decorations do not show up.
---This setting allows the use of the VS Code Diagnostic Collection to render spelling issues.
---
---```lua
---default = {
---  ["vscode-scm"] = true
---}
---```
---@field doNotUseCustomDecorationForScheme? table
---Enable / Disable checking file types (languageIds).
---
---These are in additional to the file types specified by `#cSpell.enabledLanguageIds#`.
---To disable a language, prefix with `!` as in `!json`,
---
---
---**Example: individual file types**
---
---```
---jsonc       // enable checking for jsonc
---!json       // disable checking for json
---kotlin      // enable checking for kotlin
---```
---
---**Example: enable all file types**
---
---```
---*           // enable checking for all file types
---!json       // except for json
---```
---@field enableFiletypes? string[]
---Enable / Disable the spell checker.
---
---```lua
---default = true
---```
---@field enabled? boolean
---Enable / Disable checking file types (languageIds).
---
---This setting replaces: `#cSpell.enabledLanguageIds#` and `#cSpell.enableFiletypes#`.
---
---A Value of:
---- `true` - enable checking for the file type
---- `false` - disable checking for the file type
---
---A file type of `*` is a wildcard that enables all file types.
---
---**Example: enable all file types**
---
---| File Type | Enabled | Comment |
---| --------- | ------- | ------- |
---| `*`       | `true`  | Enable all file types. |
---| `json`    | `false` | Disable checking for json files. |
---
---```lua
---default = {
---  ["*"] = true,
---  markdown = true
---}
---```
---@field enabledFileTypes? table
---Specify a list of file types to spell check. It is better to use `#cSpell.enabledFileTypes#` to Enable / Disable checking files types.
---@field enabledLanguageIds? string[]
---Control which notifications are displayed.
---
---See:
---- `#cSpell.blockCheckingWhenLineLengthGreaterThan#`
---- `#cSpell.blockCheckingWhenTextChunkSizeGreaterThan#`
---- `#cSpell.blockCheckingWhenAverageChunkSizeGreaterThan#`
---
---```lua
---default = {
---  ["Average Word Length too Long"] = true,
---  ["Lines too Long"] = true,
---  ["Maximum Word Length Exceeded"] = true
---}
---```
---@field enabledNotifications? _.lspconfig.settings.cspell_ls.CSpell.EnabledNotifications
---Control which file schemes will be checked for spelling (VS Code must be restarted for this setting to take effect).
---
---
---Some schemes have special meaning like:
---- `untitled` - Used for new documents that have not yet been saved
---- `vscode-notebook-cell` - Used for validating segments of a Notebook.
---- `vscode-userdata` - Needed to spell check `.code-snippets`
---- `vscode-scm` - Needed to spell check Source Control commit messages.
---- `comment` - Used for new comment editors.
---
---```lua
---default = {
---  comment = true,
---  file = true,
---  gist = true,
---  repo = true,
---  sftp = true,
---  untitled = true,
---  ["vscode-notebook-cell"] = true,
---  ["vscode-scm"] = true,
---  ["vscode-userdata"] = true,
---  ["vscode-vfs"] = true,
---  vsls = true
---}
---```
---@field enabledSchemes? table
---Specify compatible engine versions.
---
---This allows dictionaries and other components to specify the versions of engines (like cspell) they are compatible with.
---
---It does not enforce compatibility, it is up to the client to use this information as needed.
---@field engines? _.lspconfig.settings.cspell_ls.CSpell.Engines
---@field experimental? _.lspconfig.settings.cspell_ls.CSpell.Experimental
---Glob patterns of files to be checked.
---Glob patterns are relative to the `#cSpell.globRoot#` of the configuration file that defines them.
---@field files? string[]
---Use Rename Provider when fixing spelling issues.
---
---```lua
---default = true
---```
---@field fixSpellingWithRenameProvider? boolean
---List of words to always be considered incorrect. Words found in `flagWords` override `words`.
---
---Format of `flagWords`
---- single word entry - `word`
---- with suggestions - `word:suggestion` or `word->suggestion, suggestions`
---
---Example:
---```ts
---"flagWords": [
---  "color: colour",
---  "incase: in case, encase",
---  "canot->cannot",
---  "cancelled->canceled"
---]
---```
---@field flagWords? string[]
---The root to use for glob patterns found in this configuration.
---Default: The current workspace folder.
---Use `globRoot` to define a different location. `globRoot` can be relative to the location of this configuration file.
---Defining globRoot, does not impact imported configurations.
---
---Special Values:
---
---- `${workspaceFolder}` - Default - globs will be relative to the current workspace folder
---- `${workspaceFolder:<name>}` - Where `<name>` is the name of the workspace folder.
---@field globRoot? string
---Hide the options to add words to dictionaries or settings.
---@field hideAddToDictionaryCodeActions? boolean
---Control how spelling issues are displayed while typing.
---See: `#cSpell.revealIssuesAfterDelayMS#` to control when issues are revealed.
---
---```lua
---default = "Word"
---```
---@field hideIssuesWhileTyping? "Off" | "Word" | "Line" | "Document"
---Glob patterns of files to be ignored. The patterns are relative to the `#cSpell.globRoot#` of the configuration file that defines them.
---
---```lua
---default = { "package-lock.json", "node_modules", "vscode-extension", ".git/{info,lfs,logs,refs,objects}/**", ".git/{index,*refs,*HEAD}", ".vscode", ".vscode-insiders" }
---```
---@field ignorePaths? string[]
---Ignore sequences of characters that look like random strings.
---
---```lua
---default = true
---```
---@field ignoreRandomStrings? boolean
---List of regular expressions or Pattern names (defined in `#cSpell.patterns#`) to exclude from spell checking.
---
---- When using the VS Code Preferences UI, it is not necessary to escape the `\`, VS Code takes care of that.
---- When editing the VS Code `settings.json` file,
---  it is necessary to escape `\`.
---  Each `\` becomes `\\`.
---
---The default regular expression flags are `gi`. Add `u` (`gui`), to enable Unicode.
---
---| VS Code UI          | settings.json         | Description                                  |
---| :------------------ | :-------------------- | :------------------------------------------- |
---| `/\\[a-z]+/gi`      | `/\\\\[a-z]+/gi`      | Exclude LaTeX command like `\mapsto`         |
---| `/\b[A-Z]{3,5}\b/g` | `/\\b[A-Z]{3,5}\\b/g` | Exclude full-caps acronyms of 3-5 length.    |
---| `CStyleComment`     | `CStyleComment`       | A built in pattern                           |
---@field ignoreRegExpList? string[]
---A list of words to be ignored by the spell checker.
---@field ignoreWords? string[]
---Allows this configuration to inherit configuration for one or more other files.
---
---See [Importing / Extending Configuration](https://cspell.org/configuration/imports/) for more details.
---@field import? string[]
---List of regular expression patterns or defined pattern names to match for spell checking.
---
---If this property is defined, only text matching the included patterns will be checked.
---@field includeRegExpList? string[]
---Current active spelling language.
---
---Example: `en-GB` for British English
---
---Example: `en,nl` to enable both English and Dutch
---
---```lua
---default = "en"
---```
---@field language? string
---Additional settings for individual programming languages and locales.
---@field languageSettings? table[]
---Decoration for light themes.
---
---See:
---- `#cSpell.overviewRulerColor#`
---- `#cSpell.textDecoration#`
---@field light? _.lspconfig.settings.cspell_ls.CSpell.Light
---Have the logs written to a file instead of to VS Code.
---@field logFile? string
---Set the Debug Level for logging messages.
---
---```lua
---default = "Error"
---```
---@field logLevel? "None" | "Error" | "Warning" | "Information" | "Debug"
---The maximum number of times the same word can be flagged as an error in a file.
---
---```lua
---default = 20
---```
---@field maxDuplicateProblems? number
---The Maximum size of a file to spell check. This is used to prevent spell checking very large files.
---
---The value can be number or a string formatted `<number>[units]`, number with optional units.
---
---Supported units:
---
---- K, KB - value * 1024
---- M, MB - value * 2^20
---- G, GB - value * 2^30
---
---Special values:
---- `0` - has the effect of removing the limit.
---
---Examples:
---- `1000000` - 1 million bytes
---- `1000K` or `1000KB` - 1 thousand kilobytes
---- `0.5M` or `0.5MB` - 0.5 megabytes
---
---default: no limit
---@field maxFileSize? number|string
---Controls the maximum number of spelling errors per document.
---
---```lua
---default = 100
---```
---@field maxNumberOfProblems? number
---Specify if fields from `.vscode/settings.json` are passed to the spell checker.
---This only applies when there is a CSpell configuration file in the workspace.
---
---The purpose of this setting to help provide a consistent result compared to the
---CSpell spell checker command line tool.
---
---Values:
---- `true` - all settings will be merged based upon `#cSpell.mergeCSpellSettingsFields#`.
---- `false` - only use `.vscode/settings.json` if a CSpell configuration is not found.
---
---Note: this setting is used in conjunction with `#cSpell.mergeCSpellSettingsFields#`.
---
---```lua
---default = true
---```
---@field mergeCSpellSettings? boolean
---Specify which fields from `.vscode/settings.json` are passed to the spell checker.
---This only applies when there is a CSpell configuration file in the workspace and
---`#cSpell.mergeCSpellSettings#` is `true`.
---
---Values:
---- `{ flagWords: true, userWords: false }` - Always allow `flagWords`, but never allow `userWords`.
---
---Example:
---```jsonc
---"cSpell.mergeCSpellSettingsFields": { "userWords": false }
---```
---
---```lua
---default = {
---  allowCompoundWords = true,
---  caseSensitive = true,
---  dictionaries = true,
---  dictionaryDefinitions = true,
---  enableGlobDot = true,
---  features = true,
---  files = true,
---  flagWords = true,
---  gitignoreRoot = true,
---  globRoot = true,
---  ignorePaths = true,
---  ignoreRegExpList = true,
---  ignoreWords = true,
---  import = true,
---  includeRegExpList = true,
---  language = true,
---  languageId = true,
---  languageSettings = true,
---  loadDefaultConfiguration = true,
---  minWordLength = true,
---  noConfigSearch = true,
---  noSuggestDictionaries = true,
---  numSuggestions = true,
---  overrides = true,
---  patterns = true,
---  pnpFiles = true,
---  reporters = true,
---  suggestWords = true,
---  useGitignore = true,
---  usePnP = true,
---  userWords = true,
---  validateDirectives = true,
---  words = true
---}
---```
---@field mergeCSpellSettingsFields? _.lspconfig.settings.cspell_ls.CSpell.MergeCSpellSettingsFields
---The minimum length of a random string to be ignored.
---
---```lua
---default = 40
---```
---@field minRandomLength? number
---The minimum length of a word before checking it against a dictionary.
---
---```lua
---default = 4
---```
---@field minWordLength? number
---Prevents searching for local configuration when checking individual documents.
---@field noConfigSearch? boolean
---Optional list of dictionaries that will not be used for suggestions.
---Words in these dictionaries are considered correct, but will not be
---used when making spell correction suggestions.
---
---Note: if a word is suggested by another dictionary, but found in
---one of these dictionaries, it will be removed from the set of
---possible suggestions.
---@field noSuggestDictionaries? string[]
---Controls the number of suggestions shown.
---
---```lua
---default = 8
---```
---@field numSuggestions? number
---Overrides are used to apply settings for specific files in your project.
---
---**Example:**
---
---```jsonc
---"cSpell.overrides": [
---  // Force `*.hrr` and `*.crr` files to be treated as `cpp` files:
---  {
---    "filename": "**/{*.hrr,*.crr}",
---    "languageId": "cpp"
---  },
---  // Force `dutch/**/*.txt` to be treated as Dutch (dictionary needs to be installed separately):
---  {
---    "filename": "**/dutch/**/*.txt",
---    "language": "nl"
---  }
---]
---```
---@field overrides? table[]
---The CSS color used to show issues in the ruler.
---
---Depends upon `#cSpell.useCustomDecorations#`.
---Disable the ruler by setting `#cSpell.showInRuler#` to `false`.
---
---See:
---- [`<color>` CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)
---- [CSS Colors, W3C Schools](https://www.w3schools.com/cssref/css_colors.php)
---- Hex colors
---
---Examples:
---- `green`
---- `DarkYellow`
---- `#ffff0080` - semi-transparent yellow.
---- `rgb(255 153 0 / 80%)`
---
---```lua
---default = "#348feb80"
---```
---@field overviewRulerColor? string
---Defines a list of patterns that can be used with the `#cSpell.ignoreRegExpList#` and
---`#cSpell.includeRegExpList#` options.
---
---**Example:**
---
---```jsonc
---"cSpell.patterns": [
---  {
---    "name": "comment-single-line",
---    "pattern": "/#.*/g"
---  },
---  {
---    "name": "comment-multi-line",
---    "pattern": "/(?:\\/\\*[\\s\\S]*?\\*\\/)/g"
---  }
---]
---```
---@field patterns? table[]
---By default, the spell checker reports all unknown words as misspelled. This setting allows for a more relaxed spell checking, by only
---reporting unknown words as suggestions. Common spelling errors are still flagged as misspelled.
---
---- `all` - report all unknown words as misspelled
---- `simple` - report unknown words with simple fixes and the rest as suggestions
---- `typos` - report on known typo words and the rest as suggestions
---- `flagged` - report only flagged words as misspelled
---
---**Note:** This setting is deprecated. Use `#cSpell.unknownWords#` instead.
---@field reportUnknownWords? "all" | "simple" | "typos" | "flagged"
---Reveal hidden issues related to `#cSpell.hideIssuesWhileTyping#` after a delay in milliseconds.
---
---```lua
---default = 1500
---```
---@field revealIssuesAfterDelayMS? number
---Show CSpell in-document directives as you type.
---
---**Note:** VS Code must be restarted for this setting to take effect.
---
---```lua
---default = true
---```
---@field showAutocompleteDirectiveSuggestions? boolean
---Show Spell Checker actions in Editor Context Menu
---
---```lua
---default = true
---```
---@field showCommandsInEditorContextMenu? boolean
---Show spelling issues in the editor ruler.
---
---Note: This setting is only used when `#cSpell.useCustomDecorations#` is `true`.
---
---Note: To set the color of the ruler, use `#cSpell.overviewRulerColor#`.
---
---```lua
---default = true
---```
---@field showInRuler? boolean
---Display the spell checker status on the status bar.
---
---```lua
---default = true
---```
---@field showStatus? boolean
---The side of the status bar to display the spell checker status.
---
---```lua
---default = "Right"
---```
---@field showStatusAlignment? "Left" | "Right"
---Show Spelling Suggestions link in the top level context menu.
---
---```lua
---default = true
---```
---@field showSuggestionsLinkInEditorContextMenu? boolean
---Delay in ms after a document has changed before checking it for spelling errors.
---
---```lua
---default = 50
---```
---@field spellCheckDelayMs? number
---Only spell check files that are in the currently open workspace.
---This same effect can be achieved using the `#cSpell.files#` setting.
---
---
---```js
---"cSpell.files": ["/**"]
---```
---@field spellCheckOnlyWorkspaceFiles? boolean
---The set of available substitutions. This is a collection of substitution definitions that can be applied to a document before spell checking.
---@field substitutionDefinitions? table[]
---The set of substitutions to apply to a document before spell checking.
---@field substitutions? any[]
---A list of suggested replacements for words.
---Suggested words provide a way to make preferred suggestions on word replacements.
---To hint at a preferred change, but not to require it.
---
---Format of `suggestWords`
---- Single suggestion (possible auto fix)
---    - `word: suggestion`
---    - `word->suggestion`
---- Multiple suggestions (not auto fixable)
---   - `word: first, second, third`
---   - `word->first, second, third`
---@field suggestWords? string[]
---The type of menu used to display spelling suggestions.
---
---```lua
---default = "quickPick"
---```
---@field suggestionMenuType? "quickPick" | "quickFix"
---The maximum number of changes allowed on a word to be considered a suggestions.
---
---For example, appending an `s` onto `example` -> `examples` is considered 1 change.
---
---Range: between 1 and 5.
---
---```lua
---default = 3
---```
---@field suggestionNumChanges? number
---The maximum amount of time in milliseconds to generate suggestions for a word.
---
---```lua
---default = 400
---```
---@field suggestionsTimeout? number
---The CSS Style used to decorate spelling issues. Depends upon `#cSpell.useCustomDecorations#`.
---
---This setting is used to manually configure the text decoration. If it is not set, the following settings are used:
---- `#cSpell.textDecorationLine#` to pick the line type
---- `#cSpell.textDecorationStyle#` to pick the style
---- `#cSpell.textDecorationColor#` to set the color
---- `#cSpell.textDecorationThickness#` to set the thickness.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---
---Format:  `<line> [style] <color> [thickness]`
---
---- line - `underline`, `overline`, see: [text-decoration-line, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line)
---- style - `solid`, `wavy`, `dotted`, see: [text-decoration-style, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---- thickness - see: [text-decoration-thickness, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)
---
---Examples:
---- `underline green`
---- `underline dotted yellow 0.2rem`
---- `underline wavy #ff0c 1.5px` - Wavy underline with 1.5px thickness in semi-transparent yellow.
---
---To change the ruler color, use `#cSpell.overviewRulerColor#`.
---@field textDecoration? string
---The decoration color for normal spelling issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---To change the ruler color, use `#cSpell.overviewRulerColor#`.
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#348feb"
---```
---@field textDecorationColor? string
---The decoration color for flagged issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#f44"
---```
---@field textDecorationColorFlagged? string
---The decoration color for spelling suggestions.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- color - see: [text-decoration-color, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color)
---
---Common Format: `#RGBA` or `#RRGGBBAA` or `#RGB` or `#RRGGBB`
---
---Examples:
---- `green`
---- `yellow`
---- `#ff0c`
---
---```lua
---default = "#cf88"
---```
---@field textDecorationColorSuggestion? string
---The CSS line type used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- line - `underline`, `overline`, see: [text-decoration-line, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line)
---
---```lua
---default = "underline"
---```
---@field textDecorationLine? "underline" | "overline" | "line-through"
---The CSS line style used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- style - `solid`, `wavy`, `dotted`, see: [text-decoration-style, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style)
---
---```lua
---default = "dashed"
---```
---@field textDecorationStyle? "solid" | "wavy" | "dotted" | "dashed" | "double"
---The CSS line thickness used to decorate issues.
---
---See: [text-decoration - CSS: Cascading Style Sheets, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
---- thickness - see: [text-decoration-thickness, MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)
---
---Examples:
---- `auto`
---- `from-font`
---- `0.2rem`
---- `1.5px`
---- `10%`
---
---```lua
---default = "auto"
---```
---@field textDecorationThickness? string
---Enable loading JavaScript CSpell configuration files.
---
---This setting is automatically set to `true` in a trusted workspace. It is possible to override the setting to `false` in a trusted workspace,
---but a setting of `true` in an untrusted workspace will be ignored.
---
---See:
---- [Visual Studio Code Workspace Trust security](https://code.visualstudio.com/docs/editor/workspace-trust)
---- [Workspace Trust Extension Guide -- Visual Studio Code Extension API](https://code.visualstudio.com/api/extension-guides/workspace-trust)
---
---```lua
---default = true
---```
---@field trustedWorkspace? boolean
---Controls how unknown words are handled.
---
---- `report-all` - Report all unknown words (default behavior)
---- `report-simple` - Report unknown words that have simple spelling errors, typos, and flagged words.
---- `report-common-typos` - Report unknown words that are common typos and flagged words.
---- `report-flagged` - Report unknown words that are flagged.
---
---```lua
---default = "report-all"
---```
---@field unknownWords? "report-all" | "report-simple" | "report-common-typos" | "report-flagged"
---Draw custom decorations on Spelling Issues.
---- `true` - Use custom decorations. - VS Code Diagnostic Severity Levels are not used.
---- `false` - Use the VS Code Diagnostic Collection to render spelling issues.
---
---Note: This setting overrides the VS Code Diagnostics setting: `#cSpell.diagnosticLevel#`.
---@field useCustomDecorations? boolean
---Tells the spell checker to load `.gitignore` files and skip files that match the globs in the `.gitignore` files found.
---
---```lua
---default = true
---```
---@field useGitignore? boolean
---Search for `@cspell/cspell-bundled-dicts` in the workspace folder and use it if found.
---
---```lua
---default = true
---```
---@field useLocallyInstalledCSpellDictionaries? boolean
---Packages managers like Yarn 2 use a `.pnp.cjs` file to assist in loading
---packages stored in the repository.
---
---When true, the spell checker will search up the directory structure for the existence
---of a PnP file and load it.
---@field usePnP? boolean
---Words to add to global dictionary -- should only be in the user config file.
---@field userWords? string[]
---Verify that the in-document directives are correct.
---@field validateDirectives? boolean
---Files to add to the CSpell Virtual File System.
---
---They can be referenced using `cspell-vfs:///<module>/<path-to-file>/<file-name>` URLs.
---
---They can be referenced in the `path` field of dictionary definitions.
---@field vfs? table
---List of words to be considered correct.
---@field words? string[]
---Define the path to the workspace root folder in a multi-root workspace.
---By default it is the first folder.
---
---This is used to find the `cspell.json` file for the workspace.
---
---
---**Example: use the `client` folder**
---```
---${workspaceFolder:client}
---```
---@field workspaceRootPath? string

---@class lspconfig.settings.cspell_ls
---@field cSpell? _.lspconfig.settings.cspell_ls.CSpell
